### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by ZVH1** [creedthegamer/Rolimons-Logger#1]
How do I set this up for myself?

**Comment by creedthegamer** [comment]
Upload the files to your website file manager, and enter your webhook in config.php file :)

**Comment by ZVH1** [comment]
Thanks! Also, could you give me some ideas as how to do this? I want to have a site and have the visitor be able to put in a webhook and then when the code is run it gets sent to that webhook and the webhook in config.json. Any ideas as how to achive that?
